[workspace]
resolver = "3"
members = [
    "examples/custom-roles",
    "examples/distributed",
    "examples/oauth2-github",
    "examples/permission-registry",
    "examples/permission-validation",
    "examples/prometheus",
    "examples/rate-limiting",
    "examples/simple-usage",
    "webgates",
    "webgates-core",
    "webgates-codecs",
    "webgates-axum",
    "webgates-tonic",
    "webgates-repositories",
    "webgates-repositories/examples/sea-orm",
    "webgates-repositories/examples/surrealdb",
    "webgates-secrets",
    "webgates-sessions",
]

[workspace.dependencies]
argon2 = { version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
cookie = { version = "0.18" }
dotenvy = "0.15"
jsonwebtoken = { version = "11", features = ["rust_crypto"] }
oauth2 = { version = "5", features = ["reqwest"] }
prometheus = "0.14"
rand = "0.10"
reqwest = { version = "0.13.1", default-features = false, features = ["json", "rustls"] }
roaring = "0.11"
sea-orm = { version = "2" }
sea-query = { version = "1.0.1", default-features = false, features = ["backend-sqlite", "derive", "sea-query-derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28", features = ["derive"] }
subtle = ">=2.6.1"
thiserror = "2"
tokio = { version = "1", default-features = false }
tonic = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
uuid = { version = "1" }

[workspace.package]
rust-version = "1.94"

[profile.dev]
debug = false
