[package]
name = "surrealdb-example"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = "0.8"
chrono = { workspace = true }
dotenvy = { workspace = true }
surrealdb = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
webgates = { path = "../../../webgates" }
webgates-axum = { path = "../../../webgates-axum" }
webgates-codecs = { path = "../../../webgates-codecs" }
webgates-repositories = { path = "../../", features = ["surrealdb"] }
