[package]
name = "webgates-repositories"
version = "0.1.0-dev"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["Lewin Probst <info@emirror.de>"]
description = "Repository implementations for the webgates authentication and authorization domain."
homepage = "https://github.com/emirror-de/webgates"
repository = "https://github.com/emirror-de/webgates"
readme = "README.md"
documentation = "https://docs.rs/webgates-repositories"
keywords = ["auth", "jwt", "rbac"]
categories = ["authentication"]

[package.metadata.docs.rs]
features = [
    "repo-surrealdb",
    "repo-seaorm",
]

[features]
default = ["server"]

server = [
    "webgates/server",
    "dep:tokio",
]

audit-logging = [
]

repo-surrealdb = [
    "server",
    "dep:surrealdb",
    "dep:argon2",
]

repo-seaorm = [
    "server",
    "dep:sea-orm",
    "dep:sea-query",
    "dep:argon2",
]

[dependencies]
webgates = { path = "../webgates", default-features = true, features = ["server"] }
strum = { workspace = true }
thiserror = { workspace = true }
argon2 = { workspace = true, features = ["std"], optional = true }
tokio = { workspace = true, optional = true, features = ["rt-multi-thread", "macros"] }
sea-orm = { workspace = true, optional = true }
sea-query = { workspace = true, optional = true }
surrealdb = { workspace = true, optional = true }
subtle = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7", "js"] }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
