[package]
name = "webgates"
version = "0.1.0-dev"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["Lewin Probst <info@emirror.de>"]
description = "Core domain models and services for webgates authentication and authorization."
homepage = "https://github.com/emirror-de/webgates"
repository = "https://github.com/emirror-de/webgates"
readme = "README.md"
documentation = "https://docs.rs/webgates"
keywords = ["auth", "jwt", "rbac"]
categories = ["authentication"]

[package.metadata.docs.rs]
features = ["authn", "cookies", "oauth2", "audit-logging", "prometheus", "secrets"]

[features]
default = []
wasm = ["uuid/js"]

codecs = [
    "dep:chrono",
    "dep:serde_json",
    "dep:serde_with",
    "dep:webgates-codecs",
]

secrets = [
    "dep:rand",
    "dep:subtle",
    "dep:webgates-secrets",
]

repositories = ["dep:webgates-repositories"]

cookies = ["dep:cookie"]

oauth2 = [
    "codecs",
    "cookies",
    "dep:oauth2",
    "repositories",
]

authn = [
    "codecs",
    "repositories",
    "secrets",
    "tokio/rt-multi-thread",
    "dep:tracing",
]

audit-logging = ["dep:tracing"]
prometheus = ["audit-logging", "dep:prometheus"]

[dependencies]
chrono = { workspace = true, optional = true }
const-crypto = "0.3"
cookie = { workspace = true, optional = true }
jsonwebtoken = { workspace = true }
oauth2 = { workspace = true, optional = true }
prometheus = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
roaring = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_with = { version = "3", optional = true }
strum = { workspace = true }
subtle = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde", "v7", "js"] }
webgates-core = { path = "../webgates-core" }
webgates-codecs = { path = "../webgates-codecs", optional = true }
webgates-repositories = { path = "../webgates-repositories", optional = true }
webgates-secrets = { path = "../webgates-secrets", optional = true }

[dev-dependencies]
surrealdb = { workspace = true, features = ["kv-mem"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.4"
uuid = "1"
webgates-repositories = { path = "../webgates-repositories", features = ["sea-orm", "surrealdb"] }

[profile.dev]
debug = false
