[package]
name = "simple-usage-example"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }
webgates = { path = "../../webgates" }
webgates-repositories = { path = "../../webgates-repositories" }
webgates-axum = { path = "../../webgates-axum" }
chrono = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
